server:
  port: 8761
spring:
  application:
    name: example-discovery
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    home-page-url: http://localhost:${server.port}
    health-check-url: ${eureka.instance.home-page-url}/${server.servlet.context-path}/actuator/health
    status-page-url: ${eureka.instance.home-page-url}/${server.servlet.context-path}/actuator/info
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/