server:
  port: 8092
spring:
  application:
    name: example-pay-server
  datasource:
    platform: h2
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
swagger:
  enabled: true
  title: example-pay-server
  description: 对外提供缴费接口
  base-package: example.pay.server.web.controller
  version: 1.0.0